// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'AIzaSyAZpAOUSHwaqMqDeOtj2xU4jn0OOPBJjMo',
      appId: '1:464396711047:android:1968dc330ff224cd98b422',
      messagingSenderId: '464396711047',
      projectId: 'forum-e-fast',
      authDomain: 'forum-e-fast.firebaseapp.com',
      storageBucket: 'forum-e-fast.firebasestorage.app',
    );
  }
}
