// Mocks generated by Mockito 5.4.6 from annotations
// in forum_e_fast/test/repositories/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:cloud_firestore/cloud_firestore.dart' as _i8;
import 'package:firebase_auth/firebase_auth.dart' as _i2;
import 'package:firebase_service/firebase_service.dart' as _i6;
import 'package:firebase_service/models/comment.dart' as _i5;
import 'package:firebase_service/models/forum_post.dart' as _i3;
import 'package:firebase_service/models/reply.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForumPost_1 extends _i1.SmartFake implements _i3.ForumPost {
  _FakeForumPost_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReply_2 extends _i1.SmartFake implements _i4.Reply {
  _FakeReply_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeComment_3 extends _i1.SmartFake implements _i5.Comment {
  _FakeComment_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseService extends _i1.Mock implements _i6.FirebaseService {
  MockFirebaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.User> signUp({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i7.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.User>);

  @override
  _i7.Future<_i2.User> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {#email: email, #password: password}),
            returnValue: _i7.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#login, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.User>);

  @override
  _i7.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Stream<_i2.User?> authStateChanges() =>
      (super.noSuchMethod(
            Invocation.method(#authStateChanges, []),
            returnValue: _i7.Stream<_i2.User?>.empty(),
          )
          as _i7.Stream<_i2.User?>);

  @override
  _i7.Future<_i3.ForumPost> createPost({
    required String? content,
    required String? authorId,
    required String? authorName,
    required String? authorAvatar,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #content: content,
              #authorId: authorId,
              #authorName: authorName,
              #authorAvatar: authorAvatar,
            }),
            returnValue: _i7.Future<_i3.ForumPost>.value(
              _FakeForumPost_1(
                this,
                Invocation.method(#createPost, [], {
                  #content: content,
                  #authorId: authorId,
                  #authorName: authorName,
                  #authorAvatar: authorAvatar,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.ForumPost>);

  @override
  _i7.Future<List<_i3.ForumPost>> getPostsPaginated({
    required int? limit,
    _i8.DocumentSnapshot<Object?>? startAfter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPostsPaginated, [], {
              #limit: limit,
              #startAfter: startAfter,
            }),
            returnValue: _i7.Future<List<_i3.ForumPost>>.value(
              <_i3.ForumPost>[],
            ),
          )
          as _i7.Future<List<_i3.ForumPost>>);

  @override
  _i7.Stream<List<_i3.ForumPost>> getPostsStream({required int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getPostsStream, [], {#limit: limit}),
            returnValue: _i7.Stream<List<_i3.ForumPost>>.empty(),
          )
          as _i7.Stream<List<_i3.ForumPost>>);

  @override
  _i7.Future<_i3.ForumPost> getPostDetail(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getPostDetail, [postId]),
            returnValue: _i7.Future<_i3.ForumPost>.value(
              _FakeForumPost_1(
                this,
                Invocation.method(#getPostDetail, [postId]),
              ),
            ),
          )
          as _i7.Future<_i3.ForumPost>);

  @override
  _i7.Future<void> deletePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [postId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i4.Reply> createReply({
    required String? postId,
    required String? content,
    required String? authorId,
    required String? authorName,
    required String? authorAvatar,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createReply, [], {
              #postId: postId,
              #content: content,
              #authorId: authorId,
              #authorName: authorName,
              #authorAvatar: authorAvatar,
            }),
            returnValue: _i7.Future<_i4.Reply>.value(
              _FakeReply_2(
                this,
                Invocation.method(#createReply, [], {
                  #postId: postId,
                  #content: content,
                  #authorId: authorId,
                  #authorName: authorName,
                  #authorAvatar: authorAvatar,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.Reply>);

  @override
  _i7.Future<List<_i4.Reply>> getRepliesPaginated({
    required String? postId,
    required int? limit,
    _i8.DocumentSnapshot<Object?>? startAfter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRepliesPaginated, [], {
              #postId: postId,
              #limit: limit,
              #startAfter: startAfter,
            }),
            returnValue: _i7.Future<List<_i4.Reply>>.value(<_i4.Reply>[]),
          )
          as _i7.Future<List<_i4.Reply>>);

  @override
  _i7.Stream<List<_i4.Reply>> getRepliesStream({
    required String? postId,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getRepliesStream, [], {
              #postId: postId,
              #limit: limit,
            }),
            returnValue: _i7.Stream<List<_i4.Reply>>.empty(),
          )
          as _i7.Stream<List<_i4.Reply>>);

  @override
  _i7.Future<void> likeReply(String? replyId) =>
      (super.noSuchMethod(
            Invocation.method(#likeReply, [replyId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> deleteReply(String? replyId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteReply, [replyId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i5.Comment> createComment({
    required String? postId,
    required String? replyId,
    required String? content,
    required String? authorId,
    required String? authorName,
    required String? authorAvatar,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createComment, [], {
              #postId: postId,
              #replyId: replyId,
              #content: content,
              #authorId: authorId,
              #authorName: authorName,
              #authorAvatar: authorAvatar,
            }),
            returnValue: _i7.Future<_i5.Comment>.value(
              _FakeComment_3(
                this,
                Invocation.method(#createComment, [], {
                  #postId: postId,
                  #replyId: replyId,
                  #content: content,
                  #authorId: authorId,
                  #authorName: authorName,
                  #authorAvatar: authorAvatar,
                }),
              ),
            ),
          )
          as _i7.Future<_i5.Comment>);

  @override
  _i7.Future<List<_i5.Comment>> getCommentsPaginated({
    required String? replyId,
    required int? limit,
    _i8.DocumentSnapshot<Object?>? startAfter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCommentsPaginated, [], {
              #replyId: replyId,
              #limit: limit,
              #startAfter: startAfter,
            }),
            returnValue: _i7.Future<List<_i5.Comment>>.value(<_i5.Comment>[]),
          )
          as _i7.Future<List<_i5.Comment>>);

  @override
  _i7.Stream<List<_i5.Comment>> getCommentsStream({
    required String? replyId,
    required int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCommentsStream, [], {
              #replyId: replyId,
              #limit: limit,
            }),
            returnValue: _i7.Stream<List<_i5.Comment>>.empty(),
          )
          as _i7.Stream<List<_i5.Comment>>);

  @override
  _i7.Future<void> deleteComment(String? commentId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComment, [commentId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
