// Mocks generated by Mockito 5.4.6 from annotations
// in forum_e_fast/test/blocs/forum_posts_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_firestore/cloud_firestore.dart' as _i5;
import 'package:firebase_service/firebase_service_exports.dart' as _i2;
import 'package:forum_e_fast/repositories/forum_posts_repository.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeForumPost_0 extends _i1.SmartFake implements _i2.ForumPost {
  _FakeForumPost_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ForumPostsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockForumPostsRepository extends _i1.Mock
    implements _i3.ForumPostsRepository {
  MockForumPostsRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ForumPost> createPost({
    required String? content,
    required String? authorId,
    required String? authorName,
    required String? authorAvatar,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [], {
              #content: content,
              #authorId: authorId,
              #authorName: authorName,
              #authorAvatar: authorAvatar,
            }),
            returnValue: _i4.Future<_i2.ForumPost>.value(
              _FakeForumPost_0(
                this,
                Invocation.method(#createPost, [], {
                  #content: content,
                  #authorId: authorId,
                  #authorName: authorName,
                  #authorAvatar: authorAvatar,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ForumPost>);

  @override
  _i4.Future<List<_i2.ForumPost>> getPostsPaginated({
    required int? limit,
    _i5.DocumentSnapshot<Object?>? startAfter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPostsPaginated, [], {
              #limit: limit,
              #startAfter: startAfter,
            }),
            returnValue: _i4.Future<List<_i2.ForumPost>>.value(
              <_i2.ForumPost>[],
            ),
          )
          as _i4.Future<List<_i2.ForumPost>>);

  @override
  _i4.Stream<List<_i2.ForumPost>> getPostsStream({required int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#getPostsStream, [], {#limit: limit}),
            returnValue: _i4.Stream<List<_i2.ForumPost>>.empty(),
          )
          as _i4.Stream<List<_i2.ForumPost>>);

  @override
  _i4.Future<void> deletePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [postId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
